sudo: required
language: c
os:
  - linux
  - osx
osx_image: xcode9.3
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then brew update; else true; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then brew install libsodium swig lua graphviz doxygen protobuf-c meson; else true; fi"
script:
  - "git submodule update --init --recursive"
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash; else true; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then bash run-ci.sh; else true; fi"
arch:
  packages:
    - clang-analyzer
    - libsodium
    - valgrind
    - swig
    - lua
    - doxygen
    - graphviz
    - protobuf-c
    - meson
  script:
      - "bash run-ci.sh"
