sudo: required

arch:
  packages:
    - cmake
    - clang-analyzer
    - libsodium
    - valgrind
  script:
      - "bash run-ci.sh"
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
