/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nineteen_eighty_four_not_molch_Molch */

#ifndef _Included_de_nineteen_eighty_four_not_molch_Molch
#define _Included_de_nineteen_eighty_four_not_molch_Molch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getUserIdSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getUserIdSize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getConversationIdSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getConversationIdSize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getBackupKeySize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getBackupKeySize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    createUser
 * Signature: (ZLjava/util/Optional;)Lde/nineteen/eighty/four/not/molch/Molch/CreateUserResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_createUser
  (JNIEnv *, jclass, jboolean, jobject);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    destroyUser
 * Signature: ([BZ)Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_destroyUser
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    countUsers
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_countUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    destroyAllUsers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_destroyAllUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    listUsers
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_listUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getMessageType
 * Signature: ([B)Lde/nineteen/eighty/four/not/molch/MessageType;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getMessageType
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    startSendConversation
 * Signature: ([B[B[B[BZ)Lde/nineteen/eighty/four/not/molch/Molch/SendConversationResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_startSendConversation
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    startReceiveConversation
 * Signature: ([B[B[BZ)Lde/nineteen/eighty/four/not/molch/Molch/ReceiveConversationResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_startReceiveConversation
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    encrypt
 * Signature: ([B[BZ)Lde/nineteen/eighty/four/not/molch/Molch/EncryptResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    decrypt
 * Signature: ([B[BZ)Lde/nineteen/eighty/four/not/molch/Molch/DecryptResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    endConversation
 * Signature: ([BZ)Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_endConversation
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    listConversations
 * Signature: ([B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_listConversations
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    exportConversation
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_exportConversation
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    importConversation
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_importConversation
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    exportUsers
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_exportUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    importUsers
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_importUsers
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getPrekeyList
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getPrekeyList
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    updateBackupKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_updateBackupKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
