/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nineteen_eighty_four_not_molch_Molch */

#ifndef _Included_de_nineteen_eighty_four_not_molch_Molch
#define _Included_de_nineteen_eighty_four_not_molch_Molch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getUserIdSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getUserIdSize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getConversationIdSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getConversationIdSize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getBackupKeySize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getBackupKeySize
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    createUser
 * Signature: ([B)Lde/nineteen/eighty/four/not/molch/Molch/CreateUserResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_createUser
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    countUsers
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_countUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    destroyAllUsers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_destroyAllUsers
  (JNIEnv *, jclass);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    encrypt
 * Signature: ([B[BZ)Lde/nineteen/eighty/four/not/molch/Molch/EncryptResult;
 */
JNIEXPORT jobject JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     de_nineteen_eighty_four_not_molch_Molch
 * Method:    getPrekeyListExpirationDateSeconds
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_nineteen_eighty_four_not_molch_Molch_getPrekeyListExpirationDateSeconds
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
