sudo: required
language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then brew update; else true; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then brew install libsodium valgrind; else true; fi"
script:
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash; else true; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then bash run-ci.sh; else true; fi"
arch:
  packages:
    - cmake
    - clang-analyzer
    - libsodium
    - valgrind
  script:
      - "bash run-ci.sh"
