/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: backup.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "backup.pb-c.h"
void   molch__protobuf__backup__init
                     (Molch__Protobuf__Backup         *message)
{
  static const Molch__Protobuf__Backup init_value = MOLCH__PROTOBUF__BACKUP__INIT;
  *message = init_value;
}
size_t molch__protobuf__backup__get_packed_size
                     (const Molch__Protobuf__Backup *message)
{
  assert(message->base.descriptor == &molch__protobuf__backup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__backup__pack
                     (const Molch__Protobuf__Backup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__backup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__backup__pack_to_buffer
                     (const Molch__Protobuf__Backup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__backup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__Backup *
       molch__protobuf__backup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__Backup *)
     protobuf_c_message_unpack (&molch__protobuf__backup__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__backup__free_unpacked
                     (Molch__Protobuf__Backup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__backup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor molch__protobuf__backup__field_descriptors[1] =
{
  {
    "users",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__Backup, n_users),
    offsetof(Molch__Protobuf__Backup, users),
    &molch__protobuf__user__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__backup__field_indices_by_name[] = {
  0,   /* field[0] = users */
};
static const ProtobufCIntRange molch__protobuf__backup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor molch__protobuf__backup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.Backup",
  "Backup",
  "Molch__Protobuf__Backup",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__Backup),
  1,
  molch__protobuf__backup__field_descriptors,
  molch__protobuf__backup__field_indices_by_name,
  1,  molch__protobuf__backup__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__backup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
