/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: conversation.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "conversation.pb-c.h"
void   molch__protobuf__conversation__init
                     (Molch__Protobuf__Conversation         *message)
{
  static const Molch__Protobuf__Conversation init_value = MOLCH__PROTOBUF__CONVERSATION__INIT;
  *message = init_value;
}
size_t molch__protobuf__conversation__get_packed_size
                     (const Molch__Protobuf__Conversation *message)
{
  assert(message->base.descriptor == &molch__protobuf__conversation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__conversation__pack
                     (const Molch__Protobuf__Conversation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__conversation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__conversation__pack_to_buffer
                     (const Molch__Protobuf__Conversation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__conversation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__Conversation *
       molch__protobuf__conversation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__Conversation *)
     protobuf_c_message_unpack (&molch__protobuf__conversation__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__conversation__free_unpacked
                     (Molch__Protobuf__Conversation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__conversation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue molch__protobuf__conversation__header_decryptability__enum_values_by_number[4] =
{
  { "CURRENT_DECRYPTABLE", "MOLCH__PROTOBUF__CONVERSATION__HEADER_DECRYPTABILITY__CURRENT_DECRYPTABLE", 0 },
  { "NEXT_DECRYPTABLE", "MOLCH__PROTOBUF__CONVERSATION__HEADER_DECRYPTABILITY__NEXT_DECRYPTABLE", 1 },
  { "UNDECRYPTABLE", "MOLCH__PROTOBUF__CONVERSATION__HEADER_DECRYPTABILITY__UNDECRYPTABLE", 2 },
  { "NOT_TRIED", "MOLCH__PROTOBUF__CONVERSATION__HEADER_DECRYPTABILITY__NOT_TRIED", 3 },
};
static const ProtobufCIntRange molch__protobuf__conversation__header_decryptability__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex molch__protobuf__conversation__header_decryptability__enum_values_by_name[4] =
{
  { "CURRENT_DECRYPTABLE", 0 },
  { "NEXT_DECRYPTABLE", 1 },
  { "NOT_TRIED", 3 },
  { "UNDECRYPTABLE", 2 },
};
const ProtobufCEnumDescriptor molch__protobuf__conversation__header_decryptability__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.Conversation.HeaderDecryptability",
  "HeaderDecryptability",
  "Molch__Protobuf__Conversation__HeaderDecryptability",
  "Molch.Protobuf",
  4,
  molch__protobuf__conversation__header_decryptability__enum_values_by_number,
  4,
  molch__protobuf__conversation__header_decryptability__enum_values_by_name,
  1,
  molch__protobuf__conversation__header_decryptability__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor molch__protobuf__conversation__field_descriptors[29] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__Conversation, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_root_key),
    offsetof(Molch__Protobuf__Conversation, root_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_root_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_purported_root_key),
    offsetof(Molch__Protobuf__Conversation, purported_root_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_header_key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_send_header_key),
    offsetof(Molch__Protobuf__Conversation, send_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receive_header_key",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_receive_header_key),
    offsetof(Molch__Protobuf__Conversation, receive_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_send_header_key",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_next_send_header_key),
    offsetof(Molch__Protobuf__Conversation, next_send_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_receive_header_key",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_next_receive_header_key),
    offsetof(Molch__Protobuf__Conversation, next_receive_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_receive_header_key",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_purported_receive_header_key),
    offsetof(Molch__Protobuf__Conversation, purported_receive_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_next_receive_header_key",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_purported_next_receive_header_key),
    offsetof(Molch__Protobuf__Conversation, purported_next_receive_header_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_chain_key",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_send_chain_key),
    offsetof(Molch__Protobuf__Conversation, send_chain_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receive_chain_key",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_receive_chain_key),
    offsetof(Molch__Protobuf__Conversation, receive_chain_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_receive_chain_key",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_purported_receive_chain_key),
    offsetof(Molch__Protobuf__Conversation, purported_receive_chain_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "our_public_identity_key",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_our_public_identity_key),
    offsetof(Molch__Protobuf__Conversation, our_public_identity_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "their_public_identity_key",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_their_public_identity_key),
    offsetof(Molch__Protobuf__Conversation, their_public_identity_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "our_private_ephemeral_key",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_our_private_ephemeral_key),
    offsetof(Molch__Protobuf__Conversation, our_private_ephemeral_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "our_public_ephemeral_key",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_our_public_ephemeral_key),
    offsetof(Molch__Protobuf__Conversation, our_public_ephemeral_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "their_public_ephemeral_key",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_their_public_ephemeral_key),
    offsetof(Molch__Protobuf__Conversation, their_public_ephemeral_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "their_purported_public_ephemeral",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Conversation, has_their_purported_public_ephemeral),
    offsetof(Molch__Protobuf__Conversation, their_purported_public_ephemeral),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_message_number",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Molch__Protobuf__Conversation, has_send_message_number),
    offsetof(Molch__Protobuf__Conversation, send_message_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receive_message_number",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Molch__Protobuf__Conversation, has_receive_message_number),
    offsetof(Molch__Protobuf__Conversation, receive_message_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_message_number",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Molch__Protobuf__Conversation, has_purported_message_number),
    offsetof(Molch__Protobuf__Conversation, purported_message_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_message_number",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Molch__Protobuf__Conversation, has_previous_message_number),
    offsetof(Molch__Protobuf__Conversation, previous_message_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "purported_previous_message_number",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Molch__Protobuf__Conversation, has_purported_previous_message_number),
    offsetof(Molch__Protobuf__Conversation, purported_previous_message_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ratchet_flag",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Molch__Protobuf__Conversation, has_ratchet_flag),
    offsetof(Molch__Protobuf__Conversation, ratchet_flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "am_i_alice",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Molch__Protobuf__Conversation, has_am_i_alice),
    offsetof(Molch__Protobuf__Conversation, am_i_alice),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "received_valid",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Molch__Protobuf__Conversation, has_received_valid),
    offsetof(Molch__Protobuf__Conversation, received_valid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_decryptable",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Molch__Protobuf__Conversation, has_header_decryptable),
    offsetof(Molch__Protobuf__Conversation, header_decryptable),
    &molch__protobuf__conversation__header_decryptability__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skipped_header_and_message_keys",
    28,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__Conversation, n_skipped_header_and_message_keys),
    offsetof(Molch__Protobuf__Conversation, skipped_header_and_message_keys),
    &molch__protobuf__key_bundle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "staged_header_and_message_keys",
    29,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__Conversation, n_staged_header_and_message_keys),
    offsetof(Molch__Protobuf__Conversation, staged_header_and_message_keys),
    &molch__protobuf__key_bundle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__conversation__field_indices_by_name[] = {
  24,   /* field[24] = am_i_alice */
  26,   /* field[26] = header_decryptable */
  0,   /* field[0] = id */
  6,   /* field[6] = next_receive_header_key */
  5,   /* field[5] = next_send_header_key */
  14,   /* field[14] = our_private_ephemeral_key */
  15,   /* field[15] = our_public_ephemeral_key */
  12,   /* field[12] = our_public_identity_key */
  21,   /* field[21] = previous_message_number */
  20,   /* field[20] = purported_message_number */
  8,   /* field[8] = purported_next_receive_header_key */
  22,   /* field[22] = purported_previous_message_number */
  11,   /* field[11] = purported_receive_chain_key */
  7,   /* field[7] = purported_receive_header_key */
  2,   /* field[2] = purported_root_key */
  23,   /* field[23] = ratchet_flag */
  10,   /* field[10] = receive_chain_key */
  4,   /* field[4] = receive_header_key */
  19,   /* field[19] = receive_message_number */
  25,   /* field[25] = received_valid */
  1,   /* field[1] = root_key */
  9,   /* field[9] = send_chain_key */
  3,   /* field[3] = send_header_key */
  18,   /* field[18] = send_message_number */
  27,   /* field[27] = skipped_header_and_message_keys */
  28,   /* field[28] = staged_header_and_message_keys */
  16,   /* field[16] = their_public_ephemeral_key */
  13,   /* field[13] = their_public_identity_key */
  17,   /* field[17] = their_purported_public_ephemeral */
};
static const ProtobufCIntRange molch__protobuf__conversation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 29 }
};
const ProtobufCMessageDescriptor molch__protobuf__conversation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.Conversation",
  "Conversation",
  "Molch__Protobuf__Conversation",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__Conversation),
  29,
  molch__protobuf__conversation__field_descriptors,
  molch__protobuf__conversation__field_indices_by_name,
  1,  molch__protobuf__conversation__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__conversation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
