/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: encrypted_backup.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "encrypted_backup.pb-c.h"
void   molch__protobuf__encrypted_backup__init
                     (Molch__Protobuf__EncryptedBackup         *message)
{
  static const Molch__Protobuf__EncryptedBackup init_value = MOLCH__PROTOBUF__ENCRYPTED_BACKUP__INIT;
  *message = init_value;
}
size_t molch__protobuf__encrypted_backup__get_packed_size
                     (const Molch__Protobuf__EncryptedBackup *message)
{
  assert(message->base.descriptor == &molch__protobuf__encrypted_backup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__encrypted_backup__pack
                     (const Molch__Protobuf__EncryptedBackup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__encrypted_backup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__encrypted_backup__pack_to_buffer
                     (const Molch__Protobuf__EncryptedBackup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__encrypted_backup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__EncryptedBackup *
       molch__protobuf__encrypted_backup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__EncryptedBackup *)
     protobuf_c_message_unpack (&molch__protobuf__encrypted_backup__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__encrypted_backup__free_unpacked
                     (Molch__Protobuf__EncryptedBackup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__encrypted_backup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue molch__protobuf__encrypted_backup__backup_type__enum_values_by_number[2] =
{
  { "FULL_BACKUP", "MOLCH__PROTOBUF__ENCRYPTED_BACKUP__BACKUP_TYPE__FULL_BACKUP", 0 },
  { "CONVERSATION_BACKUP", "MOLCH__PROTOBUF__ENCRYPTED_BACKUP__BACKUP_TYPE__CONVERSATION_BACKUP", 1 },
};
static const ProtobufCIntRange molch__protobuf__encrypted_backup__backup_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex molch__protobuf__encrypted_backup__backup_type__enum_values_by_name[2] =
{
  { "CONVERSATION_BACKUP", 1 },
  { "FULL_BACKUP", 0 },
};
const ProtobufCEnumDescriptor molch__protobuf__encrypted_backup__backup_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.EncryptedBackup.BackupType",
  "BackupType",
  "Molch__Protobuf__EncryptedBackup__BackupType",
  "Molch.Protobuf",
  2,
  molch__protobuf__encrypted_backup__backup_type__enum_values_by_number,
  2,
  molch__protobuf__encrypted_backup__backup_type__enum_values_by_name,
  1,
  molch__protobuf__encrypted_backup__backup_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor molch__protobuf__encrypted_backup__field_descriptors[4] =
{
  {
    "backup_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__EncryptedBackup, backup_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backup_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Molch__Protobuf__EncryptedBackup, has_backup_type),
    offsetof(Molch__Protobuf__EncryptedBackup, backup_type),
    &molch__protobuf__encrypted_backup__backup_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_backup_nonce",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__EncryptedBackup, has_encrypted_backup_nonce),
    offsetof(Molch__Protobuf__EncryptedBackup, encrypted_backup_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_backup",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__EncryptedBackup, has_encrypted_backup),
    offsetof(Molch__Protobuf__EncryptedBackup, encrypted_backup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__encrypted_backup__field_indices_by_name[] = {
  1,   /* field[1] = backup_type */
  0,   /* field[0] = backup_version */
  3,   /* field[3] = encrypted_backup */
  2,   /* field[2] = encrypted_backup_nonce */
};
static const ProtobufCIntRange molch__protobuf__encrypted_backup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor molch__protobuf__encrypted_backup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.EncryptedBackup",
  "EncryptedBackup",
  "Molch__Protobuf__EncryptedBackup",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__EncryptedBackup),
  4,
  molch__protobuf__encrypted_backup__field_descriptors,
  molch__protobuf__encrypted_backup__field_indices_by_name,
  1,  molch__protobuf__encrypted_backup__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__encrypted_backup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
