/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: key_bundle.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "key_bundle.pb-c.h"
void   molch__protobuf__key_bundle__init
                     (Molch__Protobuf__KeyBundle         *message)
{
  static const Molch__Protobuf__KeyBundle init_value = MOLCH__PROTOBUF__KEY_BUNDLE__INIT;
  *message = init_value;
}
size_t molch__protobuf__key_bundle__get_packed_size
                     (const Molch__Protobuf__KeyBundle *message)
{
  assert(message->base.descriptor == &molch__protobuf__key_bundle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__key_bundle__pack
                     (const Molch__Protobuf__KeyBundle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__key_bundle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__key_bundle__pack_to_buffer
                     (const Molch__Protobuf__KeyBundle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__key_bundle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__KeyBundle *
       molch__protobuf__key_bundle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__KeyBundle *)
     protobuf_c_message_unpack (&molch__protobuf__key_bundle__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__key_bundle__free_unpacked
                     (Molch__Protobuf__KeyBundle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__key_bundle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor molch__protobuf__key_bundle__field_descriptors[3] =
{
  {
    "header_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__KeyBundle, header_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__KeyBundle, message_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiration_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Molch__Protobuf__KeyBundle, has_expiration_time),
    offsetof(Molch__Protobuf__KeyBundle, expiration_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__key_bundle__field_indices_by_name[] = {
  2,   /* field[2] = expiration_time */
  0,   /* field[0] = header_key */
  1,   /* field[1] = message_key */
};
static const ProtobufCIntRange molch__protobuf__key_bundle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor molch__protobuf__key_bundle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.KeyBundle",
  "KeyBundle",
  "Molch__Protobuf__KeyBundle",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__KeyBundle),
  3,
  molch__protobuf__key_bundle__field_descriptors,
  molch__protobuf__key_bundle__field_indices_by_name,
  1,  molch__protobuf__key_bundle__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__key_bundle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
