/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "packet.pb-c.h"
void   molch__protobuf__packet__init
                     (Molch__Protobuf__Packet         *message)
{
  static const Molch__Protobuf__Packet init_value = MOLCH__PROTOBUF__PACKET__INIT;
  *message = init_value;
}
size_t molch__protobuf__packet__get_packed_size
                     (const Molch__Protobuf__Packet *message)
{
  assert(message->base.descriptor == &molch__protobuf__packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__packet__pack
                     (const Molch__Protobuf__Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__packet__pack_to_buffer
                     (const Molch__Protobuf__Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__Packet *
       molch__protobuf__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__Packet *)
     protobuf_c_message_unpack (&molch__protobuf__packet__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__packet__free_unpacked
                     (Molch__Protobuf__Packet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor molch__protobuf__packet__field_descriptors[3] =
{
  {
    "packet_header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__Packet, packet_header),
    &molch__protobuf__packet_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_axolotl_header",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Packet, has_encrypted_axolotl_header),
    offsetof(Molch__Protobuf__Packet, encrypted_axolotl_header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_message",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__Packet, has_encrypted_message),
    offsetof(Molch__Protobuf__Packet, encrypted_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__packet__field_indices_by_name[] = {
  1,   /* field[1] = encrypted_axolotl_header */
  2,   /* field[2] = encrypted_message */
  0,   /* field[0] = packet_header */
};
static const ProtobufCIntRange molch__protobuf__packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor molch__protobuf__packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.Packet",
  "Packet",
  "Molch__Protobuf__Packet",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__Packet),
  3,
  molch__protobuf__packet__field_descriptors,
  molch__protobuf__packet__field_indices_by_name,
  1,  molch__protobuf__packet__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
