/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: packet_header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "packet_header.pb-c.h"
void   molch__protobuf__packet_header__init
                     (Molch__Protobuf__PacketHeader         *message)
{
  static const Molch__Protobuf__PacketHeader init_value = MOLCH__PROTOBUF__PACKET_HEADER__INIT;
  *message = init_value;
}
size_t molch__protobuf__packet_header__get_packed_size
                     (const Molch__Protobuf__PacketHeader *message)
{
  assert(message->base.descriptor == &molch__protobuf__packet_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__packet_header__pack
                     (const Molch__Protobuf__PacketHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__packet_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__packet_header__pack_to_buffer
                     (const Molch__Protobuf__PacketHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__packet_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__PacketHeader *
       molch__protobuf__packet_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__PacketHeader *)
     protobuf_c_message_unpack (&molch__protobuf__packet_header__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__packet_header__free_unpacked
                     (Molch__Protobuf__PacketHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__packet_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue molch__protobuf__packet_header__packet_type__enum_values_by_number[2] =
{
  { "PREKEY_MESSAGE", "MOLCH__PROTOBUF__PACKET_HEADER__PACKET_TYPE__PREKEY_MESSAGE", 0 },
  { "NORMAL_MESSAGE", "MOLCH__PROTOBUF__PACKET_HEADER__PACKET_TYPE__NORMAL_MESSAGE", 1 },
};
static const ProtobufCIntRange molch__protobuf__packet_header__packet_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex molch__protobuf__packet_header__packet_type__enum_values_by_name[2] =
{
  { "NORMAL_MESSAGE", 1 },
  { "PREKEY_MESSAGE", 0 },
};
const ProtobufCEnumDescriptor molch__protobuf__packet_header__packet_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.PacketHeader.PacketType",
  "PacketType",
  "Molch__Protobuf__PacketHeader__PacketType",
  "Molch.Protobuf",
  2,
  molch__protobuf__packet_header__packet_type__enum_values_by_number,
  2,
  molch__protobuf__packet_header__packet_type__enum_values_by_name,
  1,
  molch__protobuf__packet_header__packet_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Molch__Protobuf__PacketHeader__PacketType molch__protobuf__packet_header__packet_type__default_value = MOLCH__PROTOBUF__PACKET_HEADER__PACKET_TYPE__NORMAL_MESSAGE;
static const ProtobufCFieldDescriptor molch__protobuf__packet_header__field_descriptors[8] =
{
  {
    "current_protocol_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__PacketHeader, current_protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "highest_supported_protocol_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__PacketHeader, highest_supported_protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Molch__Protobuf__PacketHeader, has_packet_type),
    offsetof(Molch__Protobuf__PacketHeader, packet_type),
    &molch__protobuf__packet_header__packet_type__descriptor,
    &molch__protobuf__packet_header__packet_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_nonce",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__PacketHeader, has_header_nonce),
    offsetof(Molch__Protobuf__PacketHeader, header_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_nonce",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__PacketHeader, has_message_nonce),
    offsetof(Molch__Protobuf__PacketHeader, message_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_identity_key",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__PacketHeader, has_public_identity_key),
    offsetof(Molch__Protobuf__PacketHeader, public_identity_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_ephemeral_key",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__PacketHeader, has_public_ephemeral_key),
    offsetof(Molch__Protobuf__PacketHeader, public_ephemeral_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_prekey",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Molch__Protobuf__PacketHeader, has_public_prekey),
    offsetof(Molch__Protobuf__PacketHeader, public_prekey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__packet_header__field_indices_by_name[] = {
  0,   /* field[0] = current_protocol_version */
  3,   /* field[3] = header_nonce */
  1,   /* field[1] = highest_supported_protocol_version */
  4,   /* field[4] = message_nonce */
  2,   /* field[2] = packet_type */
  6,   /* field[6] = public_ephemeral_key */
  5,   /* field[5] = public_identity_key */
  7,   /* field[7] = public_prekey */
};
static const ProtobufCIntRange molch__protobuf__packet_header__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 16, 5 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor molch__protobuf__packet_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.PacketHeader",
  "PacketHeader",
  "Molch__Protobuf__PacketHeader",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__PacketHeader),
  8,
  molch__protobuf__packet_header__field_descriptors,
  molch__protobuf__packet_header__field_indices_by_name,
  2,  molch__protobuf__packet_header__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__packet_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
