/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: user.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "user.pb-c.h"
void   molch__protobuf__user__init
                     (Molch__Protobuf__User         *message)
{
  static const Molch__Protobuf__User init_value = MOLCH__PROTOBUF__USER__INIT;
  *message = init_value;
}
size_t molch__protobuf__user__get_packed_size
                     (const Molch__Protobuf__User *message)
{
  assert(message->base.descriptor == &molch__protobuf__user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t molch__protobuf__user__pack
                     (const Molch__Protobuf__User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &molch__protobuf__user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t molch__protobuf__user__pack_to_buffer
                     (const Molch__Protobuf__User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &molch__protobuf__user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Molch__Protobuf__User *
       molch__protobuf__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Molch__Protobuf__User *)
     protobuf_c_message_unpack (&molch__protobuf__user__descriptor,
                                allocator, len, data);
}
void   molch__protobuf__user__free_unpacked
                     (Molch__Protobuf__User *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &molch__protobuf__user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor molch__protobuf__user__field_descriptors[7] =
{
  {
    "private_signing_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__User, private_signing_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_signing_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__User, public_signing_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_identity_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__User, private_identity_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_identity_key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Molch__Protobuf__User, public_identity_key),
    &molch__protobuf__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conversations",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__User, n_conversations),
    offsetof(Molch__Protobuf__User, conversations),
    &molch__protobuf__conversation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prekeys",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__User, n_prekeys),
    offsetof(Molch__Protobuf__User, prekeys),
    &molch__protobuf__prekey__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deprecated_prekeys",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Molch__Protobuf__User, n_deprecated_prekeys),
    offsetof(Molch__Protobuf__User, deprecated_prekeys),
    &molch__protobuf__prekey__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned molch__protobuf__user__field_indices_by_name[] = {
  4,   /* field[4] = conversations */
  6,   /* field[6] = deprecated_prekeys */
  5,   /* field[5] = prekeys */
  2,   /* field[2] = private_identity_key */
  0,   /* field[0] = private_signing_key */
  3,   /* field[3] = public_identity_key */
  1,   /* field[1] = public_signing_key */
};
static const ProtobufCIntRange molch__protobuf__user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor molch__protobuf__user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Molch.Protobuf.User",
  "User",
  "Molch__Protobuf__User",
  "Molch.Protobuf",
  sizeof(Molch__Protobuf__User),
  7,
  molch__protobuf__user__field_descriptors,
  molch__protobuf__user__field_indices_by_name,
  1,  molch__protobuf__user__number_ranges,
  (ProtobufCMessageInit) molch__protobuf__user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
