dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
notifications:
  email:
    recipients:
      - nialldouglas14@gmail.com

env:
 - __="Build"
 - __="Test"
 - __="Install"

install: "pip install -r requirements.txt"

script:
 -
   if [ "$__" = "Build" ]; then
     python setup.py build;
   fi
 -
   if [ "$__" = "Test" ]; then
     python setup.py test;
   fi
 -
   if [ "$__" = "Install" ]; then
     python setup.py install;
     pcpp --version;
   fi
 -
   if [ "$__" = "Documentation" ]; then
     git config --global push.default simple;
     git config --global user.name "Jenkins nedprod CI";
     git config --global user.email "foo@nowhere";
     cd doc/html;
     git checkout gh-pages;
     cd ../..;
     ctest -S .docs.cmake -V;
     cd doc/html;
     git add . || true;
     git commit -a -m "Travis CI updates documentation" || true;
     git push -f https://jenkins-nedprod:$JENKINS_NEDPROD_PASSWORD@github.com/ned14/boost.outcome gh-pages;
     cd ../..;
   fi
