version: '1.0.{build}'

image:
    - Visual Studio 2017
    - Visual Studio 2015

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - generator: "Visual Studio 15 2017"
        - generator: "Visual Studio 14 2015"
        - generator: "Visual Studio 12 2013"
        - generator: "Visual Studio 11 2012"
        - generator: "Visual Studio 10 2010"

matrix:
    fast_finish: true
    exclude:
        - image:      Visual Studio 2015
          generator: "Visual Studio 15 2017"
        - image:      Visual Studio 2017
          generator: "Visual Studio 14 2015"
        - image:      Visual Studio 2017
          generator: "Visual Studio 12 2013"
        - image:      Visual Studio 2017
          generator: "Visual Studio 11 2012"
        - image:      Visual Studio 2017
          generator: "Visual Studio 10 2010"

before_build:
    - mkdir build && cd build
    - cmake -A %platform% -G "%generator%" -DGSL_LITE_OPT_BUILD_TESTS=ON -DGSL_LITE_OPT_BUILD_EXAMPLES=ON ..

build_script:
    - cmake --build . --config %configuration%
    - ctest -C %configuration%
